openapi: 3.0.1
info:
  title: OCR Plugin
  description: A plugin that allows users to extract text from images and PDF documents using Optical Character Recognition (OCR) with ChatGPT.
  version: 'v1'
servers:
  - url: http://127.0.0.1:5000
paths:
  /ocr:
    post:
      operationId: ocr
      summary: Extract text from an image or PDF document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The image or PDF document to be processed
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ocrResponse'
components:
  schemas:
    ocrResponse:
      type: array
      items:
        type: string
      description: A list of extracted texts from the image or PDF document
